<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProcesoCompraSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        try {
            DB::table('procesos_compras')->delete();

            DB::table('procesos_compras')->insert([
            [
                'id' => 2,
                'nombre_proceso' => 'Alquiler de Mobiliarios para eventos',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-29 21:12:45',
                'updated_at' => '2024-01-29 21:12:45',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 3,
                'nombre_proceso' => 'ÚTILES DE OFICINA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-29 21:37:08',
                'updated_at' => '2024-01-30 19:29:52',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 4,
                'nombre_proceso' => 'AGUA PURIFICADA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-29 21:37:40',
                'updated_at' => '2024-01-30 19:30:03',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 5,
                'nombre_proceso' => 'ACCESORIOS PARA CÁMARA FOTOGRÁFICA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 15:58:56',
                'updated_at' => '2024-01-30 15:58:56',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 6,
                'nombre_proceso' => 'ACCESORIOS Y REPUESTOS TECNOLÓGICOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 16:00:02',
                'updated_at' => '2024-01-30 16:00:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 7,
                'nombre_proceso' => 'ALIMENTO CONCENTRADO ACUICULTURA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 16:01:08',
                'updated_at' => '2024-01-30 16:01:08',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 9,
                'nombre_proceso' => 'ALQUILER DE SALÓN GRADUACIONES #1',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 16:02:01',
                'updated_at' => '2024-01-30 16:02:01',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 10,
                'nombre_proceso' => 'ALQUILER DE SALÓN GRADUACIONES #2',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 16:02:27',
                'updated_at' => '2024-01-30 16:02:27',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 11,
                'nombre_proceso' => 'ALQUILER MESAS, CARPAS Y MANTELES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:04:51',
                'updated_at' => '2024-01-30 17:04:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 12,
                'nombre_proceso' => 'ALQUILER DE SONIDO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:05:11',
                'updated_at' => '2024-01-30 17:05:11',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 13,
                'nombre_proceso' => 'ARENA DE RÍO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:05:40',
                'updated_at' => '2024-01-30 17:05:40',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 14,
                'nombre_proceso' => 'BASE PARA CONO SUAVE',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:06:04',
                'updated_at' => '2024-01-30 17:06:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 15,
                'nombre_proceso' => 'BATERÍAS ALCALINAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:06:22',
                'updated_at' => '2024-01-30 17:06:22',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 16,
                'nombre_proceso' => 'BOLSAS PARA EMPAQUE AL VACÍO LÁCTEOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:06:48',
                'updated_at' => '2024-01-30 17:06:48',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 17,
                'nombre_proceso' => 'BOLSAS PLÁSTICAS PARA VIVERO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:12:17',
                'updated_at' => '2024-01-30 17:12:17',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 18,
                'nombre_proceso' => 'CABINAS Y MODULARES PARA LABORATORIO DE LENGUAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:12:54',
                'updated_at' => '2024-01-30 17:12:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 19,
                'nombre_proceso' => 'CAFÉ, AZUCAR Y GALLETAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:13:23',
                'updated_at' => '2024-01-30 17:13:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 20,
                'nombre_proceso' => 'CÁÑAMO DE HILO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:13:52',
                'updated_at' => '2024-01-30 17:13:52',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 21,
                'nombre_proceso' => 'CHALECO SEGURIDAD LABORAL',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:14:23',
                'updated_at' => '2024-01-30 17:14:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 22,
                'nombre_proceso' => 'AIRES ACONDICIONADOS (COMPRA E INSTALACIÓN)',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:14:47',
                'updated_at' => '2024-05-09 09:22:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 10,
                'deleted_by' => NULL,
            ],
            [
                'id' => 23,
                'nombre_proceso' => 'COMPRA E INSTALACIÓN BOMBA SUMERGIBLE DEL POZO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:15:05',
                'updated_at' => '2024-01-30 17:15:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 24,
                'nombre_proceso' => 'DESECHABLES PLÁSTICOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:17:43',
                'updated_at' => '2024-01-30 17:17:43',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 25,
                'nombre_proceso' => 'DÍESEL',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:18:26',
                'updated_at' => '2024-01-30 17:18:26',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 26,
                'nombre_proceso' => 'DISPENSADOR DE PAPEL',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:18:45',
                'updated_at' => '2024-01-30 17:18:45',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 28,
                'nombre_proceso' => 'ELEMENTOS Y MATERIALES PARA LIMPIEZA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:20:12',
                'updated_at' => '2024-01-30 17:20:12',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 29,
                'nombre_proceso' => 'ENVASES PE JUGO LECHE',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:20:47',
                'updated_at' => '2024-01-30 17:20:47',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 30,
                'nombre_proceso' => 'EQUIPO ELECTRÓNICO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:21:03',
                'updated_at' => '2024-01-30 17:21:03',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 31,
                'nombre_proceso' => 'EXTRACCIÓN DESECHOS SÓLIDOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:21:20',
                'updated_at' => '2024-01-30 17:21:20',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 32,
                'nombre_proceso' => 'FRASCOS DE VIDRIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:22:30',
                'updated_at' => '2024-01-30 17:22:30',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 33,
                'nombre_proceso' => 'GASOLINA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:22:42',
                'updated_at' => '2024-01-30 17:22:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 34,
                'nombre_proceso' => 'GLOBOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:22:49',
                'updated_at' => '2024-01-30 17:22:49',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 35,
                'nombre_proceso' => 'GUANTES DE CUERO PARA LABORATORIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:23:24',
                'updated_at' => '2024-01-30 17:23:24',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 36,
                'nombre_proceso' => 'INSECTICIDAS Y FUMIGANTES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:23:42',
                'updated_at' => '2024-01-30 17:23:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 37,
                'nombre_proceso' => 'INSUMOS Y MATERIALES LABORATORIO CIENCIAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:24:02',
                'updated_at' => '2024-01-30 17:24:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 38,
                'nombre_proceso' => 'LEASSING COMPUTADORAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:24:18',
                'updated_at' => '2024-01-30 17:24:18',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 39,
                'nombre_proceso' => 'LICENCIAS DE SOFTWARE',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:24:37',
                'updated_at' => '2024-01-30 17:24:37',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 40,
                'nombre_proceso' => 'LIMPIADORES DE CONTACTO Y ESPUMA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:24:53',
                'updated_at' => '2024-01-30 17:24:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 41,
                'nombre_proceso' => 'LIMPIEZA Y AFORO DEL POZO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:25:10',
                'updated_at' => '2024-01-30 17:25:10',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 42,
                'nombre_proceso' => 'LLANTAS PARA VEHÍCULOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:25:23',
                'updated_at' => '2024-01-30 17:25:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 43,
                'nombre_proceso' => 'DESINFECTANTE EN AEROSOL (LYSOL)',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:25:51',
                'updated_at' => '2024-01-30 17:25:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 44,
                'nombre_proceso' => 'MANTEL',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:27:40',
                'updated_at' => '2024-01-30 17:27:40',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 45,
                'nombre_proceso' => 'MANTENIMIENTO AIRES ACONDICIONADOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:27:55',
                'updated_at' => '2024-01-30 17:27:55',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 46,
                'nombre_proceso' => 'MANTENIMIENTO BLOWERS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:28:07',
                'updated_at' => '2024-01-30 17:28:07',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 47,
                'nombre_proceso' => 'MANTENIMIENTO EDIFICIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:40:17',
                'updated_at' => '2024-01-30 17:40:17',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 48,
                'nombre_proceso' => 'MANTENIMIENTO EQUIPO AGROINDUSTRIA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:40:29',
                'updated_at' => '2024-01-30 17:40:29',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 49,
                'nombre_proceso' => 'MANTENIMIENTO EQUIPO LABORATORIO CIENCIAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:40:47',
                'updated_at' => '2024-01-30 17:40:47',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 50,
                'nombre_proceso' => 'MANTENIMIENTO GEOMEMBRANAS LABORATORIO HÚMEDO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:41:22',
                'updated_at' => '2024-01-30 17:41:22',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 51,
                'nombre_proceso' => 'MANTENIMIENTO INSTALACIÓN ELÉCTRICA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:42:22',
                'updated_at' => '2024-01-30 17:42:22',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 52,
                'nombre_proceso' => 'MANTENIMIENTO PODADORAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:42:32',
                'updated_at' => '2024-01-30 17:42:32',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 53,
                'nombre_proceso' => 'MANTENIMIENTO RECIRCULACIÓN LAB HÚMEDO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 17:42:56',
                'updated_at' => '2024-01-30 17:42:56',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 54,
                'nombre_proceso' => 'MANTENIMIENTO SILLA ODONTOLÓGICA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:42:54',
                'updated_at' => '2024-01-30 18:42:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 55,
                'nombre_proceso' => 'MANTENIMIENTO TERMONEBULIZADORAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:43:11',
                'updated_at' => '2024-01-30 18:43:11',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 56,
                'nombre_proceso' => 'MANTENIMIENTO VEHÍCULOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:43:28',
                'updated_at' => '2024-01-30 18:43:28',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 57,
                'nombre_proceso' => 'MATERIALES ELÉCTRICOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:43:42',
                'updated_at' => '2024-01-30 18:43:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 58,
                'nombre_proceso' => 'MATERIALES FERRETEROS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:48:34',
                'updated_at' => '2024-01-30 18:48:34',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 59,
                'nombre_proceso' => 'MATERIALES ODONTOLÓGICOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:48:43',
                'updated_at' => '2024-01-30 18:48:43',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 60,
                'nombre_proceso' => 'MATERIALES PARA PESCA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:48:56',
                'updated_at' => '2024-01-30 18:48:56',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 61,
                'nombre_proceso' => 'MEDALLAS VOAE',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:49:07',
                'updated_at' => '2024-01-30 18:49:07',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 62,
                'nombre_proceso' => 'MEDICAMENTOS VOAE',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:49:22',
                'updated_at' => '2024-01-30 18:49:22',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 63,
                'nombre_proceso' => 'MERIENDAS/ALMUERZOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:53:33',
                'updated_at' => '2024-01-30 18:53:33',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 64,
                'nombre_proceso' => 'MOBILIARIO Y EQUIPO DE OFICINA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:53:47',
                'updated_at' => '2024-01-30 18:53:47',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 65,
                'nombre_proceso' => 'MOTOR AGROINDUSTRIA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:54:51',
                'updated_at' => '2024-01-30 18:54:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 66,
                'nombre_proceso' => 'PAPEL IMPRESORAS URI',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:55:06',
                'updated_at' => '2024-01-30 18:55:06',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 67,
                'nombre_proceso' => 'PASAJES AEREOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:55:18',
                'updated_at' => '2024-01-30 18:55:18',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 68,
                'nombre_proceso' => 'PECES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:55:29',
                'updated_at' => '2024-01-30 18:55:29',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 69,
                'nombre_proceso' => 'PINTURAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:56:55',
                'updated_at' => '2024-01-30 18:56:55',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 70,
                'nombre_proceso' => 'PLACA RECONOCIMIENTO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:57:05',
                'updated_at' => '2024-01-30 18:57:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 71,
                'nombre_proceso' => 'PRODUCTOS ARTES GRÁFICAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 18:57:23',
                'updated_at' => '2024-01-30 18:57:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 72,
                'nombre_proceso' => 'PUERTAS VIDRIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:18:07',
                'updated_at' => '2024-01-30 19:18:07',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 73,
                'nombre_proceso' => 'REFRESCOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:18:30',
                'updated_at' => '2024-01-30 19:18:30',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 74,
                'nombre_proceso' => 'SELLOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:18:38',
                'updated_at' => '2024-01-30 19:18:38',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 75,
                'nombre_proceso' => 'SISTEMA MODULAR PÁNELES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:18:51',
                'updated_at' => '2024-01-30 19:18:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 76,
                'nombre_proceso' => 'TELA PARA LIENZO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:22:25',
                'updated_at' => '2024-01-30 19:22:25',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 77,
                'nombre_proceso' => 'TIERRA DE ABONO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:22:35',
                'updated_at' => '2024-01-30 19:22:35',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 78,
                'nombre_proceso' => 'TRAJES PARA FUMIGAR',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:22:44',
                'updated_at' => '2024-01-30 19:22:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 79,
                'nombre_proceso' => 'TRIPA CERDO PARA CHORIZO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:28:06',
                'updated_at' => '2024-01-30 19:28:06',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 80,
                'nombre_proceso' => 'TROFEOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:28:15',
                'updated_at' => '2024-01-30 19:28:15',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 81,
                'nombre_proceso' => 'UTENSILIOS COCINA LAB AGROINDUSTRIA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:28:33',
                'updated_at' => '2024-01-30 19:28:33',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 82,
                'nombre_proceso' => 'ÚTILES DEPORTIVOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:29:01',
                'updated_at' => '2024-01-30 19:29:01',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 83,
                'nombre_proceso' => 'LECHE DE VACA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:29:18',
                'updated_at' => '2024-01-30 19:29:18',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 84,
                'nombre_proceso' => 'CUAJO DE LECHE',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-30 19:29:24',
                'updated_at' => '2024-01-30 19:29:24',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 85,
                'nombre_proceso' => 'LEASING DE IMPRESORAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-01-31 18:10:23',
                'updated_at' => '2024-01-31 18:10:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 86,
                'nombre_proceso' => 'EQUIPO AGROINDUSTRIAL',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-02-02 19:56:24',
                'updated_at' => '2024-02-02 19:56:24',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 87,
                'nombre_proceso' => 'PROTEINA PARA PECES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-02-19 20:20:26',
                'updated_at' => '2024-02-19 20:20:26',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 88,
                'nombre_proceso' => 'EQUIPO DE LABORATORIO CIENCIAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-02-19 20:57:49',
                'updated_at' => '2024-02-19 20:57:49',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 89,
                'nombre_proceso' => 'CARPAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-02-19 21:10:45',
                'updated_at' => '2024-02-19 21:10:45',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 90,
                'nombre_proceso' => 'EQUIPO DE LABORATORIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-04 10:53:53',
                'updated_at' => '2024-07-04 10:53:53',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 91,
                'nombre_proceso' => 'PIZARRA DE VIDRIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-08 10:38:10',
                'updated_at' => '2024-07-08 10:38:10',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 92,
                'nombre_proceso' => 'ABRAZADERAS PLASTICAS (PAQUETE DE BRIDAS)',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-08 11:14:39',
                'updated_at' => '2024-07-08 11:14:39',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 93,
                'nombre_proceso' => 'TABLEROS MDF PERFORADOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-08 11:21:04',
                'updated_at' => '2024-07-08 11:21:04',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 94,
                'nombre_proceso' => 'GUANTES PLASTICOS, USO ALIMENTARIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-08 15:11:42',
                'updated_at' => '2024-07-08 15:11:42',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 95,
                'nombre_proceso' => 'HERRAMIENTAS MAYORES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-08 15:24:14',
                'updated_at' => '2024-07-08 15:24:14',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 96,
                'nombre_proceso' => 'SERVICIOS DE CAPACITACION',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 08:49:28',
                'updated_at' => '2024-07-10 08:49:28',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 97,
                'nombre_proceso' => 'SERVICIO DE LAMINADO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 08:55:47',
                'updated_at' => '2024-07-10 08:55:47',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 98,
                'nombre_proceso' => 'PASTA TERMICA PARA PC',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 10:20:00',
                'updated_at' => '2024-07-10 10:20:00',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 99,
                'nombre_proceso' => 'ALQUILER DE SALON PARA EVENTOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 10:29:27',
                'updated_at' => '2024-07-10 10:29:27',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 100,
                'nombre_proceso' => 'KIT DESARMADOR DE PRECISION',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 10:34:09',
                'updated_at' => '2024-07-10 10:34:09',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 101,
                'nombre_proceso' => 'MATENIMIENTO PREVENTIVO Y CORRECTIVO EQUIPO TECNOLOGICO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 10:44:47',
                'updated_at' => '2024-07-10 10:44:47',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 102,
                'nombre_proceso' => 'INSTALACION DE EQUIPO TECNOLOGICO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 10:47:19',
                'updated_at' => '2024-07-10 10:47:19',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 103,
                'nombre_proceso' => 'CONTROL REMOTO INTELIGENTE WIFI CONEXION INFRAROJO UNIVERSAL',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 10:56:02',
                'updated_at' => '2024-07-10 10:56:02',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 104,
                'nombre_proceso' => 'CAMARA DE SEGURIDAD',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 10:57:35',
                'updated_at' => '2024-07-10 10:57:35',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 105,
                'nombre_proceso' => 'GRABADORES DE VIDEOVIGILANCIA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:00:02',
                'updated_at' => '2024-07-10 11:00:02',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 106,
                'nombre_proceso' => 'ADAPTADORES DE VGA A HDMI',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:09:00',
                'updated_at' => '2024-07-10 11:09:00',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 107,
                'nombre_proceso' => 'ADAPTADORES DE TARJETA DE RED RJ45 A USB',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:11:08',
                'updated_at' => '2024-07-10 11:11:08',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 108,
                'nombre_proceso' => 'ADAPTADORES DE RED WIFI POR MEDIO DE USB',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:12:33',
                'updated_at' => '2024-07-10 11:12:33',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 109,
                'nombre_proceso' => 'BATERIA PARA COMPUTADORA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:18:01',
                'updated_at' => '2024-07-10 11:18:01',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 110,
                'nombre_proceso' => 'CONECTORES RJ45',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:20:33',
                'updated_at' => '2024-07-10 11:20:33',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 111,
                'nombre_proceso' => 'VIDEO BALUNS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:25:42',
                'updated_at' => '2024-07-10 11:25:42',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 112,
                'nombre_proceso' => 'GABINETE DE RACK',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:27:39',
                'updated_at' => '2024-07-10 11:27:39',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 113,
                'nombre_proceso' => 'EXTENSION DE MECHAS DE AUDIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:31:44',
                'updated_at' => '2024-07-10 11:31:44',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 114,
                'nombre_proceso' => 'LAMPARA LED DE ESCRITORIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:35:35',
                'updated_at' => '2024-07-10 11:35:35',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 115,
                'nombre_proceso' => 'WEB CAM',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:45:59',
                'updated_at' => '2024-07-10 11:45:59',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 116,
                'nombre_proceso' => 'MANTENIMIENTO CORRECTIVO DE UPS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 11:47:55',
                'updated_at' => '2024-07-10 11:50:32',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 117,
                'nombre_proceso' => 'GORRA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 12:22:13',
                'updated_at' => '2024-07-10 12:22:13',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 118,
                'nombre_proceso' => 'ELECTRODOMESTICOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 13:09:51',
                'updated_at' => '2024-07-10 13:09:51',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 119,
                'nombre_proceso' => 'SERVICIO DE ENMARCADO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 13:24:46',
                'updated_at' => '2024-07-10 13:24:46',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 120,
                'nombre_proceso' => 'SERVICIO DE LAVADO Y PLANCHADO DE TOGAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-10 13:56:38',
                'updated_at' => '2024-07-10 13:56:38',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 121,
                'nombre_proceso' => 'UTENSILIOS DE COCINA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 09:38:16',
                'updated_at' => '2024-07-15 09:38:16',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 122,
                'nombre_proceso' => 'PRODUCTOS DE ALIMENTOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 10:46:24',
                'updated_at' => '2024-07-15 10:46:24',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 123,
                'nombre_proceso' => 'INSTRUMENTOS MUSICALES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 11:05:03',
                'updated_at' => '2024-07-15 11:05:03',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 124,
                'nombre_proceso' => 'PRODUCTOS DE HIERRO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 11:07:42',
                'updated_at' => '2024-07-15 11:07:42',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 125,
                'nombre_proceso' => 'EQUIPO DE COMUNICACION',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 11:17:13',
                'updated_at' => '2024-07-15 11:17:13',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 126,
                'nombre_proceso' => 'CALZADO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 11:18:16',
                'updated_at' => '2024-07-15 11:18:16',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 127,
                'nombre_proceso' => 'ESPEJO DE VIDRIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 11:22:22',
                'updated_at' => '2024-07-15 11:22:22',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 128,
                'nombre_proceso' => 'CABALLETES DE MADERA PARA ARTE',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 11:24:36',
                'updated_at' => '2024-07-15 11:24:36',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 129,
                'nombre_proceso' => 'PLYWOOD',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 11:51:10',
                'updated_at' => '2024-07-15 11:51:10',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 130,
                'nombre_proceso' => 'ANGULO DE METAL',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 11:55:34',
                'updated_at' => '2024-07-15 11:55:34',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 131,
                'nombre_proceso' => 'MANTENIMIENTO DE CAMPANA DE GAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 12:02:58',
                'updated_at' => '2024-07-15 12:02:58',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 132,
                'nombre_proceso' => 'MANTENIMIENTO DE BALANZA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 12:04:45',
                'updated_at' => '2024-07-15 12:04:45',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 133,
                'nombre_proceso' => 'SPOTS PUBLICITARIOS EN MEDIOS REGIONALES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 13:19:57',
                'updated_at' => '2024-07-15 13:19:57',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 134,
                'nombre_proceso' => 'LAMINA TRAGALUZ DE TECHO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 13:35:53',
                'updated_at' => '2024-07-15 13:35:53',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 135,
                'nombre_proceso' => 'CUERDA PARA GUITARRA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 13:37:39',
                'updated_at' => '2024-07-15 13:37:39',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 136,
                'nombre_proceso' => 'JUEGOS DE MESA EDUCATIVOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 13:38:58',
                'updated_at' => '2024-07-15 13:38:58',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 137,
                'nombre_proceso' => 'SERVICIOS DE FUMIGACION',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 14:23:30',
                'updated_at' => '2024-07-15 14:23:30',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 138,
                'nombre_proceso' => 'SET DE DIAPASON',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 14:56:01',
                'updated_at' => '2024-07-15 14:56:01',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 139,
                'nombre_proceso' => 'ENCOMIENDA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 15:16:17',
                'updated_at' => '2024-07-15 15:16:17',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 140,
                'nombre_proceso' => 'LAMINA DE VIDRIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 15:17:46',
                'updated_at' => '2024-07-15 15:17:46',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 141,
                'nombre_proceso' => 'IMPUESTO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 15:18:47',
                'updated_at' => '2024-07-15 15:18:47',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 142,
                'nombre_proceso' => 'SOPORTE TV',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 15:22:21',
                'updated_at' => '2024-07-15 15:22:21',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 143,
                'nombre_proceso' => 'TIMBRES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 15:28:01',
                'updated_at' => '2024-07-15 15:28:01',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 144,
                'nombre_proceso' => 'AUTENTICA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 15:29:14',
                'updated_at' => '2024-07-15 15:29:14',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 145,
                'nombre_proceso' => 'APARATO PARA MEDIR CONDUCTIVIDAD TERMICA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-15 15:31:51',
                'updated_at' => '2024-07-15 15:31:51',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 146,
                'nombre_proceso' => 'CONSULTOR NACIONAL',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 10:07:08',
                'updated_at' => '2024-07-16 10:07:08',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 147,
                'nombre_proceso' => 'COMISIONES COMPRAS DE DIVISAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 10:08:11',
                'updated_at' => '2024-07-16 10:08:11',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 148,
                'nombre_proceso' => 'COMISIONES POR TRANSFERENCIAS INTERNACIONALES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 10:09:18',
                'updated_at' => '2024-07-16 10:09:18',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 149,
                'nombre_proceso' => 'GASTOS DE ESTADIAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 10:49:24',
                'updated_at' => '2024-07-16 10:49:24',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 150,
                'nombre_proceso' => 'CARTUCHO CONTRA OLORES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 11:14:08',
                'updated_at' => '2024-07-16 11:14:08',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 151,
                'nombre_proceso' => 'CONTRUCCION DE ESPACIOS USOS MULTIPLES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 11:42:11',
                'updated_at' => '2024-07-16 11:42:11',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 152,
                'nombre_proceso' => 'TAPETE ANTISALPICADURAS PARA URINARIOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 11:43:29',
                'updated_at' => '2024-07-16 11:43:29',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 153,
                'nombre_proceso' => 'METRO (PARA MEDIR)',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 12:22:21',
                'updated_at' => '2024-07-16 12:22:21',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 154,
                'nombre_proceso' => 'GRAVA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 14:57:36',
                'updated_at' => '2024-07-16 14:57:36',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 155,
                'nombre_proceso' => 'LADRILLO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:21:59',
                'updated_at' => '2024-07-16 15:21:59',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 156,
                'nombre_proceso' => 'VARILLA CORRUGADA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:22:56',
                'updated_at' => '2024-07-16 15:22:56',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 157,
                'nombre_proceso' => 'VARILLA LISA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:24:21',
                'updated_at' => '2024-07-16 15:24:21',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 158,
                'nombre_proceso' => 'SIFON',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:25:08',
                'updated_at' => '2024-07-16 15:25:08',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 159,
                'nombre_proceso' => 'MADERA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:26:54',
                'updated_at' => '2024-07-16 15:26:54',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 160,
                'nombre_proceso' => 'ELECTRODO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:30:56',
                'updated_at' => '2024-07-16 15:30:56',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 161,
                'nombre_proceso' => 'PORTA ELECTRODO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:32:21',
                'updated_at' => '2024-07-16 15:32:21',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 162,
                'nombre_proceso' => 'DISCO DE CORTE',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:34:21',
                'updated_at' => '2024-07-16 15:34:21',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 163,
                'nombre_proceso' => 'TUBO HG',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:35:11',
                'updated_at' => '2024-07-16 15:35:11',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 164,
                'nombre_proceso' => 'ANGULO DE HG',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:36:09',
                'updated_at' => '2024-07-16 15:36:09',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 165,
                'nombre_proceso' => 'BOMBA PARA PUERTA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:37:32',
                'updated_at' => '2024-07-16 15:37:32',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 166,
                'nombre_proceso' => 'PINES PARA PUERTA DE VIDRIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:39:07',
                'updated_at' => '2024-07-16 15:39:07',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 167,
                'nombre_proceso' => 'TOPES (PATITA) PARA PUERTA DE VIDRIO',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-16 15:40:29',
                'updated_at' => '2024-07-16 15:40:29',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 168,
                'nombre_proceso' => 'Toners y tintas',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-17 14:23:59',
                'updated_at' => '2024-07-17 14:23:59',
                'deleted_at' => NULL,
                'created_by' => 10,
                'updated_by' => 10,
                'deleted_by' => NULL,
            ],
            [
                'id' => 169,
                'nombre_proceso' => 'GASTOS FINANCIEROS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2024-07-17 14:56:33',
                'updated_at' => '2024-07-17 14:56:33',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 170,
                'nombre_proceso' => 'MAQUINARIA INDUSTRIAL',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-04-29 08:48:42',
                'updated_at' => '2025-04-29 08:48:42',
                'deleted_at' => NULL,
                'created_by' => 62,
                'updated_by' => 62,
                'deleted_by' => NULL,
            ],
            [
                'id' => 171,
                'nombre_proceso' => 'REMOLQUE PARA LANCHA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-04 11:12:43',
                'updated_at' => '2025-07-04 11:12:43',
                'deleted_at' => NULL,
                'created_by' => 62,
                'updated_by' => 62,
                'deleted_by' => NULL,
            ],
            [
                'id' => 172,
                'nombre_proceso' => 'FLOREROS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-04 11:37:53',
                'updated_at' => '2025-07-04 11:37:53',
                'deleted_at' => NULL,
                'created_by' => 62,
                'updated_by' => 62,
                'deleted_by' => NULL,
            ],
            [
                'id' => 173,
                'nombre_proceso' => 'MANTELES Y SOBREMANTELES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-04 11:38:04',
                'updated_at' => '2025-07-04 11:38:04',
                'deleted_at' => NULL,
                'created_by' => 62,
                'updated_by' => 62,
                'deleted_by' => NULL,
            ],
            [
                'id' => 174,
                'nombre_proceso' => 'REPUESTOS Y ACCESORIOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-08 09:49:58',
                'updated_at' => '2025-07-08 09:49:58',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 175,
                'nombre_proceso' => 'MATENIMIENTO DE MOTOR DE LANCHA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-08 10:15:14',
                'updated_at' => '2025-07-08 10:15:14',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 176,
                'nombre_proceso' => 'MANTENIMIENTO DE MOTOR DE LANCHA',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-08 10:16:16',
                'updated_at' => '2025-07-08 10:16:16',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 177,
                'nombre_proceso' => 'HILADOS Y TELAS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-08 13:12:10',
                'updated_at' => '2025-07-08 13:12:10',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 178,
                'nombre_proceso' => 'HERRAMIENTAS MENORES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-08 13:14:51',
                'updated_at' => '2025-07-08 13:14:51',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 179,
                'nombre_proceso' => 'PRODUCTOS FARMACEUTICOS Y MEDICINALES',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-08 13:22:37',
                'updated_at' => '2025-07-08 13:22:37',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 180,
                'nombre_proceso' => 'PRODUCTOS PLASTICOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-08 13:38:49',
                'updated_at' => '2025-07-08 13:38:49',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 181,
                'nombre_proceso' => 'PRODUCTOS QUIMICOS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-09 09:26:40',
                'updated_at' => '2025-07-09 09:26:40',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            [
                'id' => 182,
                'nombre_proceso' => 'PRODUCTOS DE CEMENTO, ASBESTO, YESO Y OTROS',
                'monto_total' => '0.00',
                'idTipoProcesoCompra' => NULL,
                'idUE' => 1,
                'idPoa' => NULL,
                'created_at' => '2025-07-09 09:31:38',
                'updated_at' => '2025-07-09 09:31:38',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
            ],
            ]);
        } finally {
            Schema::enableForeignKeyConstraints();
        }
    }
}
